spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/docker_test?serverTimezone=Asia/Seoul
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false