spring:
  profiles:
    active: local
    group:
      local: common, local-db
      prod1: common, prod-db, prod1-server
      prod2: common, prod-db, prod2-server

server:
  env: blue # ??? ?? ???? ???? ?? ? ??, ?? ?? ? ??

---

spring:
  config:
    activate:
      on-profile: common

servlet:
  multipart:
    max-file-size: 20MB
    max-request-size: 20MB

application:
  name:

serverName: common

---

spring:
  config:
    activate:
      on-profile: local-db

datasource:
  url:
  username:
  password:

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      show_sql: true
dbInfo: h2

---

spring:
  config:
    activate:
      on-profile: prod-db

datasource:
  url:
  username:
  password:

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      show_sql: true

dbInfo: rds

---

spring:
  config:
    activate:
      on-profile: prod1-server

serverName: hel-gather-prod1

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: prod2-server

serverName: hel-gather-prod2

server:
  port: 8081

---