name: Deploy Main to Ubuntu Server with Gradle and Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('/.gradle', '/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create application-prod.yml by secrets
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.YML_PROD }}" > ./application-prod.yml
        shell: bash

      # gradlew에 실행 권한을 부여
      - name: Grant Execute Permisson for Gradlew
        run: chmod +x gradlew

      # test는 CI 과정에서 수행되므로 여기서는 `-x`로 테스트를 생략
      # `--stacktrace`로 더 자세한 로그가 출력
      - name: Build with Gradle (without Test)
        run: ./gradlew clean build -x test --stacktrace

      # docker hub에 로그인
      # -u -p를 통한 로그인 시 요청이 보안오류가 발생할 수 있음
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # dockerfile을 이용해 이미지를 빌드 후 push
      # 로그인하지 않으면 push 시에 요청이 거부될 수 있음
      - name: Docker Hub build & push
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} --push .

      # Ubuntu에 접속하고 배포
      - name: Deploy to Prod Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          # docker-compose가 있는 디렉토리로 이동 후 수행
          script: |
            docker rm -f $(docker ps -qa)
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            chmod 777 ./deploy.sh
            ./deploy.sh
            docker image prune -f
